version: 2

release:
  # If set to auto, will mark the release as not ready for production in case there is an indicator for this in the
  # tag e.g. v1.0.0-rc1 .If set to true, will mark the release as not ready for production.
  prerelease: auto

  # If set to true, will not auto-publish the release. This is done to allow us to review the changelog before publishing.
  draft: false

builds:
  - id: linux-build
    binary: &name bonsai
    dir: &dir ./cmd/bonsai
    env: &build-env
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: &build-timestamp "{{ .CommitTimestamp }}"
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.version={{.Version}}
      -X main.gitCommit={{.Commit}}
      -X main.buildDate={{.Date}}
      -X main.gitDescription={{.Summary}}

  - id: darwin-build
    dir: *dir
    binary: *name
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

  - id: windows-build
    dir: *dir
    binary: *name
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

nfpms:
  - license: "Apache 2.0"
    maintainer: "Alex Goodman"
    homepage: &website "https://github.com/wagoodman/bonsai"
    description: &description "Helping you make smaller dependency trees for you Go projects."
    formats:
      - rpm
      - deb

archives:
  - id: linux-archives
    builds:
      - linux-build

  - id: darwin-archives
    builds:
      - darwin-build

  - id: windows-archives
    format: zip
    builds:
      - windows-build

sboms:
  - artifacts: archive
    cmd: ../.tool/syft
    documents:
      - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom"
    args:
      - "scan"
      - "$artifact"
      - "--output"
      - "json=$document"
